version: "3.7"

services:
    dependency-checker:
        image: dependency-checker
        container_name: dependency-checker
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./:/app"
            - "/app/node_modules"
        ports:
            - 3000:3000